language: perl
sudo: false
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"

notifications:
  slack:
    - secure: "laCF0bYPjqktV2qjYzmpXHyKDPjzPojKL905acGO7jHJX66OhxFFsVTs/Jfm58tsAWgtKCpAXQStaWAOjZSdWMpHfkvTFt8La1yGD0lY3B7H5KOzDApjc9GLa83I/S7jXMHwan4Ri4MhQZ+3NbeIkBgnry3hBR4JF538Zt4aGDMBah1UqkX9x4Eq2MStXohsuVXpTEGCQEc3niwigmPjxqHTGg/FNs/bOzx0Rv9y1/uoa5jLRDDKogC/ygNSgg7n9fomF0cApnbrvwpCahKxBBuumX/ZA0RG/JX2YtWvDCsyzTiqTxMQY/PWaTPdmX5OR1ow+gkSL93GDuFM8jhHbPRAxDxTVh+21ojhhLqpGyavrbg9XBhWPIA5cqLHo/IKpkWcxRehT3yeJHcEC+w+Lb73IuUeXx0EgHiHJ3HckWESNcMJC46w1wK8pp8/LFuXoWMirP6lQeVV5iOaUVP4b62o4U1nKpX6rO2dl52OUWxX/K1pD3tQtMjEewLMbBZxrHVH1CRCQQaLMARkEwh0Ddrasv2mOR1eWK7s+LKYh2IvVYzVFKtd7gn2auMurUJSEdc85qf0ep87z9g7VwFs/wqKVHOPJvafv/MLffD4B/N0oZ/YGefVoCrUszgfn+Ahr4zV14iqh689gNkqxGaayaADKm1u+od2cX/cH54ew8s="
