name = "Text-Diff-Unified-XS"
badges = ["github-actions/test.yml", "metacpan"]
authority = "cpan:PINE"
license = "mit"

module_maker='ModuleBuild'
markdown_maker = 'Pod::Markdown::Github'

[build]
build_class = 'builder::MyBuilder'
